### ISSUE TITLE
It is recommended to add a master-slave delay report

### ISSUE THREAD

**Issue by mawenbin666** [xiongcccc/pgcheck#1]

**Comment by xiongcccc** [comment]
有主从延迟
[postgres@xiongcc ]$ ./pgcheck replication
 client |   user   |    name     |   state   | mode  |   write_lag   |    flush_lag    |   replay_lag    
--------+----------+-------------+-----------+-------+---------------+-----------------+-----------------
        | postgres | walreceiver | streaming | async | 00:00:01.5963 | 00:00:01.603589 | 00:00:01.610971
(1 row)
